### ISSUE TITLE
Issue while running gulp task

### ISSUE THREAD

**Issue by arkroy** [Galeria-Kaufhof/gulp-galen#9]
Hi

I'm facing issues while running the gulptask. Please could you help. I'm using on Mac OSX 10.11.3  El Capitan. Please find below my Gulp task and Error on Terminal

GULPTASK ======================================================
gulp.task('test', function() {
  gulp.src(config.galen.specs).pipe(gulpGalen.check({
    url: config.galen.url,
    galenPath: gulpGalen.check({galenPath: './node_modules/.bin/galen'}),
    cwd: config.galen.test,
    htmlreport: config.galen.report
  }));
});

ERROR ON TERMINAL ======================================================
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Stream.<anonymous> (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/lib/gulp-galen.js:80:7)
    at Stream.stream.write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/node_modules/through/index.js:26:11)
    at write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform](/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)

**Comment by arty-name** [comment]
Have a look, you are calling `galen.check` twice: 

``` javascript
gulpGalen.check({
  galenPath: gulpGalen.check({galenPath: './node_modules/.bin/galen'})
})
```

You only need the outermost one.

**Comment by arkroy** [comment]
Thanks for noticing that. I've fixed the issue. New task looks as below, however does not solve the problem:

GULP TASK ------------------------------
gulp.task('test', function() {
  gulp.src('./src/specs/*_/_.gspec')
    .pipe(gulpGalen.check({
      url: config.galen.url,
      //galenPath: './node_modules/.bin/galen',
      cwd:'.src/test/',
      htmlreport: config.galen.report
  }));
})

ERROR ON TERMINAL--------------------
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Could not start galen. Galen ('/usr/local/bin/galen') not found?
    at ChildProcess.<anonymous> (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/lib/gulp-galen.js:91:30)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by arty-name** [comment]
Hmm, we do not expose the original error that comes from spawn, so it’s hard to tell. Could you modify the file `/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/lib/gulp-galen.js` and insert `console.error(err)` before the line 91? After you run the task again it should print out the original error.

**Comment by arkroy** [comment]
Thanks, I added the console and the following details popped up with the error on terminal. But I'm not able to make sense of it, can you help?

{ [Error: spawn /usr/local/bin/galen ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /usr/local/bin/galen',
  path: '/usr/local/bin/galen',
  spawnargs: 
   [ 'check',
     '/Users/ark/Desktop/FT_BuildAutomation/fti_corp/src/specs/index.gspec',
     '--url=http://192.168.0.102:3000',
     '--htmlreport=./reports' ] }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Could not start galen. Galen ('/usr/local/bin/galen') not found?
    at ChildProcess.<anonymous> (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galen/lib/gulp-galen.js:92:30)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by arty-name** [comment]
It could be that you were caught in the middle between us updating the readme in the repository and publishing the new version of the package. Is that right that you have just recently installed gulp-galen? If so, you might need to use [the older version of readme to install galen globally](https://github.com/Galeria-Kaufhof/gulp-galen/blob/18b493802de3da1395edeaa4bf46c929e961dc30/README.md). Or install gulp-galen directly from this repository. Sorry about the mismatch!

**Comment by arty-name** [comment]
Actually I have just published the latest commit in npm, so if you update to gulp-galen@1.1.1 it should work just fine.

**Comment by arkroy** [comment]
Thanks, though it still doesn't work. But I think it might be a problem with the galenframework-cli. Thanks again for your help. I'll keep you posted if I continue facing issues.
